spring:
  application:
    name: gatewayserver
  config:
    import: optional:configserver:http://localhost:8070
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: false
      httpclient:
        connect-timeout: 1000
        response-timeout: 2s

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8072